import { TechnicianProfile } from "./types.js";

export const TECHNICIANS: TechnicianProfile[] = [
  {
    name: "Nate",
    seniorityRank: 1,
    skills: [
      "senior",
      "ev",
      "service-change",
      "rough-wiring",
      "remodel_estimates",
      "panel_work",
      "residential",
      "commercial",
      "troubleshooting",
    ],
    bookingTargets: ["estimate"],
  },
  {
    name: "Brandon",
    seniorityRank: 1,
    skills: [
      "senior",
      "commercial",
      "troubleshooting",
      "residential",
      "new-plugs",
      "recessed-lighting",
      "service_calls",
      "lighting",
      "panel_work",
    ],
  },
  {
    name: "Steve",
    seniorityRank: 1,
    skills: [
      "senior",
      "commercial",
      "troubleshooting",
      "residential",
      "new-plugs",
      "recessed-lighting",
      "service_calls",
      "lighting",
    ],
  },
  {
    name: "Dave",
    seniorityRank: 2,
    skills: [
      "senior",
      "troubleshooting",
      "residential",
      "fixtures",
      "new-plugs",
      "recessed-lighting",
      "service_calls",
      "lighting",
    ],
  },
  {
    name: "Lou",
    seniorityRank: 2,
    skills: [
      "senior",
      "commercial",
      "troubleshooting",
      "residential",
      "new-plugs",
      "ev",
      "service_calls",
      "panel_work",
    ],
  },
  {
    name: "Joseph",
    seniorityRank: 2,
    skills: [
      "senior",
      "troubleshooting",
      "residential",
      "new-plugs",
      "recessed-lighting",
      "service_calls",
      "lighting",
      "panel_work",
    ],
  },
  {
    name: "Andrew",
    seniorityRank: 2,
    skills: [
      "senior",
      "commercial",
      "troubleshooting",
      "residential",
      "new-plugs",
      "recessed-lighting",
      "service_calls",
      "lighting",
    ],
  },
  {
    name: "Brayden",
    seniorityRank: 2,
    skills: [
      "senior",
      "troubleshooting",
      "residential",
      "fixtures",
      "new-plugs",
      "recessed-lighting",
      "service_calls",
      "lighting",
    ],
  },
];
