import { BookSmartConfig } from "./types.js";

export const DEFAULT_BOOKSMART_CONFIG: BookSmartConfig = {
  serviceTypes: [
    {
      id: "outlet_switch_issue",
      displayName: "Outlet or switch issue",
      category: "service_call",
      requiredSkills: ["service_calls", "troubleshooting"],
      photoRequest: "never",
      priorityLevel: 3,
      classifierPhrases: ["outlet", "switch", "receptacle", "plug"],
      requestedServiceLabel: "Outlet or switch issue",
    },
    {
      id: "breaker_tripping",
      displayName: "Breaker tripping",
      category: "service_call",
      requiredSkills: ["service_calls", "troubleshooting", "panel_work"],
      photoRequest: "never",
      priorityLevel: 4,
      classifierPhrases: ["breaker", "tripping", "trip"],
      requestedServiceLabel: "Breaker tripping",
    },
    {
      id: "flickering_lights",
      displayName: "Flickering lights",
      category: "service_call",
      requiredSkills: ["service_calls", "troubleshooting", "lighting"],
      photoRequest: "never",
      priorityLevel: 3,
      classifierPhrases: ["flickering", "flicker", "lights blinking"],
      requestedServiceLabel: "Flickering lights",
    },
    {
      id: "power_loss_partial",
      displayName: "Partial power loss",
      category: "service_call",
      requiredSkills: ["service_calls", "troubleshooting"],
      photoRequest: "never",
      priorityLevel: 4,
      classifierPhrases: ["partial power", "half the house", "some outlets out", "power loss"],
      requestedServiceLabel: "Partial power loss",
    },
    {
      id: "fixture_repair_or_replace",
      displayName: "Fixture repair or replacement",
      category: "service_call",
      requiredSkills: ["service_calls", "lighting"],
      photoRequest: "recommended",
      priorityLevel: 2,
      classifierPhrases: ["fixture", "light fixture", "replace light", "repair light"],
      requestedServiceLabel: "Fixture repair or replacement",
    },
    {
      id: "troubleshooting_general",
      displayName: "General troubleshooting",
      category: "service_call",
      requiredSkills: ["service_calls", "troubleshooting"],
      photoRequest: "never",
      priorityLevel: 3,
      classifierPhrases: ["troubleshoot", "diagnose", "electrical issue", "problem"],
      requestedServiceLabel: "General troubleshooting",
    },
    {
      id: "dedicated_circuit",
      displayName: "Dedicated circuit",
      category: "service_call",
      requiredSkills: ["service_calls", "panel_work"],
      photoRequest: "recommended",
      priorityLevel: 3,
      classifierPhrases: ["dedicated circuit", "new circuit", "dedicated line"],
      requestedServiceLabel: "Dedicated circuit",
    },
    {
      id: "smoke_co_detector",
      displayName: "Smoke or CO detector",
      category: "service_call",
      requiredSkills: ["service_calls"],
      photoRequest: "never",
      priorityLevel: 2,
      classifierPhrases: ["smoke detector", "co detector", "carbon monoxide detector"],
      requestedServiceLabel: "Smoke or CO detector",
    },
    {
      id: "outdoor_receptacle",
      displayName: "Outdoor receptacle",
      category: "service_call",
      requiredSkills: ["service_calls"],
      photoRequest: "recommended",
      priorityLevel: 2,
      classifierPhrases: ["outdoor outlet", "outdoor receptacle", "outside plug"],
      requestedServiceLabel: "Outdoor receptacle",
    },
    {
      id: "fan_or_fixture_install",
      displayName: "Fan or fixture install",
      category: "service_call",
      requiredSkills: ["service_calls", "lighting"],
      photoRequest: "recommended",
      priorityLevel: 2,
      classifierPhrases: ["fan install", "ceiling fan", "install fixture", "hang chandelier"],
      requestedServiceLabel: "Fan or fixture install",
    },
    {
      id: "ev_charger_install",
      displayName: "EV charger install",
      category: "estimate",
      requiredSkills: ["ev_chargers", "panel_work"],
      photoRequest: "recommended",
      priorityLevel: 4,
      classifierPhrases: ["ev charger", "tesla charger", "car charger"],
      requestedServiceLabel: "EV charger installation",
    },
    {
      id: "panel_upgrade",
      displayName: "Panel upgrade",
      category: "estimate",
      requiredSkills: ["panel_work"],
      photoRequest: "recommended",
      priorityLevel: 5,
      classifierPhrases: ["panel upgrade", "replace panel", "new panel"],
      requestedServiceLabel: "Panel upgrade",
    },
    {
      id: "service_upgrade",
      displayName: "Service upgrade",
      category: "estimate",
      requiredSkills: ["panel_work"],
      photoRequest: "recommended",
      priorityLevel: 5,
      classifierPhrases: ["service upgrade", "200 amp", "electrical service"],
      requestedServiceLabel: "Service upgrade",
    },
    {
      id: "remodel_project",
      displayName: "Remodel project",
      category: "estimate",
      requiredSkills: ["remodel_estimates", "lighting"],
      photoRequest: "recommended",
      priorityLevel: 4,
      classifierPhrases: ["remodel", "kitchen remodel", "basement remodel", "renovation"],
      requestedServiceLabel: "Remodel project",
    },
    {
      id: "recessed_lighting_add",
      displayName: "Recessed lighting",
      category: "estimate",
      requiredSkills: ["lighting", "remodel_estimates"],
      photoRequest: "recommended",
      priorityLevel: 3,
      classifierPhrases: ["recessed", "can lights", "pot lights"],
      requestedServiceLabel: "Recessed lighting",
    },
    {
      id: "whole_home_rewire",
      displayName: "Whole home rewire",
      category: "estimate",
      requiredSkills: ["remodel_estimates", "panel_work"],
      photoRequest: "recommended",
      priorityLevel: 5,
      classifierPhrases: ["rewire", "whole home rewire", "full rewire"],
      requestedServiceLabel: "Whole home rewire",
    },
    {
      id: "generator_or_interlock",
      displayName: "Generator or interlock",
      category: "estimate",
      requiredSkills: ["generators", "panel_work"],
      photoRequest: "recommended",
      priorityLevel: 4,
      classifierPhrases: ["generator", "interlock"],
      requestedServiceLabel: "Generator or interlock",
    },
    {
      id: "subpanel_install",
      displayName: "Subpanel install",
      category: "estimate",
      requiredSkills: ["panel_work"],
      photoRequest: "recommended",
      priorityLevel: 4,
      classifierPhrases: ["subpanel"],
      requestedServiceLabel: "Subpanel install",
    },
    {
      id: "surge_protection_upgrade",
      displayName: "Surge protection upgrade",
      category: "estimate",
      requiredSkills: ["panel_work"],
      photoRequest: "recommended",
      priorityLevel: 3,
      classifierPhrases: ["surge protection", "whole home surge"],
      requestedServiceLabel: "Surge protection upgrade",
    },
    {
      id: "smart_home_or_lutron",
      displayName: "Smart home or Lutron",
      category: "estimate",
      requiredSkills: ["smart_home", "lighting"],
      photoRequest: "recommended",
      priorityLevel: 3,
      classifierPhrases: ["lutron", "smart home", "smart switch", "smart dimmer"],
      requestedServiceLabel: "Smart home or Lutron",
    },
    {
      id: "burning_smell",
      displayName: "Burning smell",
      category: "urgent",
      requiredSkills: ["troubleshooting", "panel_work"],
      photoRequest: "never",
      priorityLevel: 10,
      classifierPhrases: ["burning smell", "smells burnt", "electrical burning"],
      requestedServiceLabel: "Burning smell",
    },
    {
      id: "sparks_or_arcing",
      displayName: "Sparks or arcing",
      category: "urgent",
      requiredSkills: ["troubleshooting", "panel_work"],
      photoRequest: "never",
      priorityLevel: 10,
      classifierPhrases: ["sparks", "arcing", "sparked"],
      requestedServiceLabel: "Sparks or arcing",
    },
    {
      id: "hot_panel",
      displayName: "Hot panel",
      category: "urgent",
      requiredSkills: ["panel_work"],
      photoRequest: "never",
      priorityLevel: 10,
      classifierPhrases: ["hot panel", "panel is hot"],
      requestedServiceLabel: "Hot panel",
    },
    {
      id: "emergency_power_issue",
      displayName: "Emergency power issue",
      category: "urgent",
      requiredSkills: ["troubleshooting"],
      photoRequest: "never",
      priorityLevel: 10,
      classifierPhrases: ["emergency power", "unsafe outage", "power emergency"],
      requestedServiceLabel: "Emergency power issue",
    },
    {
      id: "service_mast_or_meter_issue",
      displayName: "Service mast or meter issue",
      category: "urgent",
      requiredSkills: ["panel_work"],
      photoRequest: "recommended",
      priorityLevel: 10,
      classifierPhrases: ["service mast", "meter issue", "meter socket"],
      requestedServiceLabel: "Service mast or meter issue",
    },
    {
      id: "unsafe_panel_condition",
      displayName: "Unsafe panel condition",
      category: "urgent",
      requiredSkills: ["panel_work"],
      photoRequest: "recommended",
      priorityLevel: 10,
      classifierPhrases: ["unsafe panel", "rusted panel", "water in panel"],
      requestedServiceLabel: "Unsafe panel condition",
    },
  ],
  serviceAreas: {
    allowedCities: [
      "sterling heights",
      "troy",
      "rochester hills",
      "royal oak",
      "clinton township",
      "shelby township",
      "washington",
      "washington township",
      "utica",
      "madison heights",
      "oak park",
      "berkley",
      "warren",
      "fraseR".toLowerCase(),
    ],
    restrictedCities: [],
    outsideAreaBehavior: "handoff",
  },
  urgencyKeywords: [
    { phrase: "burning smell", level: "urgent" },
    { phrase: "sparks", level: "urgent" },
    { phrase: "arcing", level: "urgent" },
    { phrase: "hot panel", level: "urgent" },
    { phrase: "service mast", level: "urgent" },
    { phrase: "meter issue", level: "urgent" },
    { phrase: "unsafe panel", level: "urgent" },
    { phrase: "partial outage", level: "urgent" },
  ],
  bookingRules: {
    sameDayAllowed: true,
    minimumNoticeHours: 2,
    allowedWindows: ["morning", "afternoon"],
  },
  conversation: {
    openingQuestion: "hey - how can i help?",
    afterHoursBehavior: "continue",
    requestPhotosFor: ["estimate"],
    handoffMessage: "I’m looping in our team so they can help you right away.",
  },
};
